### ISSUE TITLE
Missing VERSION file error

### ISSUE THREAD

**Issue by WayneKeenan** [TheCellule/blesonwin#4]
Moved from: https://github.com/TheCellule/python-bleson/issues/50

**Comment by Wenlin88** [comment]
I made a minor fix and now i managed to install package without MISSING file error with  Python 3.7.6. I generated pull request for that

**Comment by khazhyk** [comment]
Noting here since the other issue is closed, you probably need a similar commit https://github.com/TheCellule/python-bleson/commit/30e3bd6a67ce4dd29d1212f4af580c98d176ea14 to for this repository, as noted in https://github.com/TheCellule/python-bleson/issues/50#issuecomment-675277883

**Comment by WayneKeenan** [comment]
ok, done.

**Comment by khazhyk** [comment]
Thanks! I think the path would want to just be VERSION since it's in the same directory as setup.py

~~pip install --upgrade 'git+https://github.com/khazhyk/python-blesonwin#egg=version_subpkg&subdirectory=blesonwin' got past the VERSION step for me,~~ although that clones the whole repo so i think is unaffected by MANIFEST anways

**Comment by WayneKeenan** [comment]
ah, done. thanks.
